Improved console interface. Spawner now is able to print report and get program name with arguments from command line.
New issue
Summary: Create platform independent sources
Move some sources from src/win32/ dir to src/ dir

New issue
Summary: Test programs with memory limit
J:\Projects\spawner\build\Debug>Spawner.exe -ml=2 net statistics server
Option, ID: 2, Text: '-ml', Argument: '2'
stderr :
22
Системная ошибка 14.
stderr :
2
--------------- Spawner report ---------------
Application:           net
Parameters:            statistics server
SecurityLevel:         0
CreateProcessMethod:
UserName:
UserTimeLimit:         INFINITE
DeadLine:              INFINITE
MemoryLimit:           2 (MB)
WriteLimit:            INFINITE
----------------------------------------------
UserTime:              0.0156001 (s)
PeakMemoryUsed:        2 (MB)
Written:               2.28882e-005 (MB)
TerminateReason:       terminate_reason_not_terminated
ExitStatus:            process_finished_abnormally
ExitCode:              2
Exception:             EXCEPTION_ACCESS_VIOLATION
ExceptionDescription:  The Process tried to read from or write to a virtual addr
ess for which it does not have the appropriate access.
----------------------------------------------
SpawnerError: