libspawner: Fix compilation errors and warnings under MinGW. pipes.cpp:265 - error: 'min' was not declared in this scope
  pipes.cpp uses min() from Windef.h where std::min() can't be used due to type mismatch.
  This works under MSVC, but not MinGW, because MinGW defines NOMINMAX for Windef.h in it's own system headers.

platform.cpp:55 - error: '_In_' was not declared in this scope
platform.cpp:69 - error: 'BOOL CancelSynchronousIo_wrapper' redeclared as different kind of symbol

  Caused by needless usage of SAL in definitions.
  Details: https://msdn.microsoft.com/en-us/library/hh916383.aspx

platform.cpp:196 - warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

  Caused by missed "const".